### PR TITLE
feat(RELEASE-1031): new breakdown dashboard

### PR DESCRIPTION
**Pull request by theflockers**
This commit adds an extra dashboard with more information about the release service.

### CODE REVIEW

**Review by johnbieren — COMMENTED** [review]
Is there a rendering of this I can see or anything? Hard to review 2.3k lines of json

**Comment by theflockers** [comment]
> Is there a rendering of this I can see or anything? Hard to review 2.3k lines of json

Sure. Some graphs won´t render as some data is not available on stage grafana.

**Comment by theflockers** [comment]
@johnbieren I changed this PR to instead, deploy it on appsre grafana, which has datasources with 1 year retention. 

https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/116242

**Review by johnbieren — APPROVED** [review]

**Comment by johnbieren** [comment]
> @johnbieren I changed this PR to instead, deploy it on appsre grafana, which has datasources with 1 year retention.
> 
> https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/116242

I approved based on what you showed in standup, as I don't really know the json as mentioned. If it is dependent on that MR, please wait til it merges to merge this

**Comment by theflockers** [comment]
> > @johnbieren I changed this PR to instead, deploy it on appsre grafana, which has datasources with 1 year retention.
> > https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/116242
> 
> I approved based on what you showed in standup, as I don't really know the json as mentioned. If it is dependent on that MR, please wait til it merges to merge this

Indeed. It is exactly what you've seen. About the other PR, it is the other way around. I need this one first, so the MR can pass the tests (as it searches for it). Thanks!

**Pull request merged**
